
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/rnsvg/RNSVGProps.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>

namespace facebook {
namespace react {

extern const char RNSVGSvgViewComponentName[];

/*
 * `ShadowNode` for <RNSVGSvgView> component.
 */
using RNSVGSvgViewShadowNode = ConcreteViewShadowNode<
    RNSVGSvgViewComponentName,
    RNSVGSvgViewProps>;

extern const char RNSVGGroupComponentName[];

/*
 * `ShadowNode` for <RNSVGGroup> component.
 */
using RNSVGGroupShadowNode = ConcreteViewShadowNode<
    RNSVGGroupComponentName,
    RNSVGGroupProps>;

extern const char RNSVGCircleComponentName[];

/*
 * `ShadowNode` for <RNSVGCircle> component.
 */
using RNSVGCircleShadowNode = ConcreteViewShadowNode<
    RNSVGCircleComponentName,
    RNSVGCircleProps>;


extern const char RNSVGPathComponentName[];

/*
 * `ShadowNode` for <RNSVGPath> component.
 */
using RNSVGPathShadowNode = ConcreteViewShadowNode<
    RNSVGPathComponentName,
    RNSVGPathProps>;

extern const char RNSVGRectComponentName[];

/*
 * `ShadowNode` for <RNSVGRect> component.
 */
using RNSVGRectShadowNode = ConcreteViewShadowNode<
    RNSVGRectComponentName,
    RNSVGRectProps>;


extern const char RNSVGEllipseComponentName[];

/*
 * `ShadowNode` for <RNSVGEllipse> component.
 */
using RNSVGEllipseShadowNode = ConcreteViewShadowNode<
    RNSVGEllipseComponentName,
    RNSVGEllipseProps>;

extern const char RNSVGLineComponentName[];

/*
 * `ShadowNode` for <RNSVGLine> component.
 */
using RNSVGLineShadowNode = ConcreteViewShadowNode<
    RNSVGLineComponentName,
    RNSVGLineProps>;

extern const char RNSVGDefsComponentName[];

/*
 * `ShadowNode` for <RNSVGDefs> component.
 */
using RNSVGDefsShadowNode = ConcreteViewShadowNode<
    RNSVGDefsComponentName,
    RNSVGDefsProps>;

extern const char RNSVGUseComponentName[];

/*
 * `ShadowNode` for <RNSVGUse> component.
 */
using RNSVGUseShadowNode = ConcreteViewShadowNode<
    RNSVGUseComponentName,
    RNSVGUseProps>;
    

extern const char RNSVGLinearGradientComponentName[];

/*
 * `ShadowNode` for <RNSVGLinearGradient> component.
 */
using RNSVGLinearGradientShadowNode = ConcreteViewShadowNode<
    RNSVGLinearGradientComponentName,
    RNSVGLinearGradientProps>;

extern const char RNSVGClipPathComponentName[];
/*
 * `ShadowNode` for <RNSVGClipPath> component.
 */
using RNSVGClipPathShadowNode = ConcreteViewShadowNode<
    RNSVGClipPathComponentName,
    RNSVGClipPathProps>;


extern const char RNSVGForeignObjectComponentName[];

/*
 * `ShadowNode` for <RNSVGForeignObject> component.
 */
using RNSVGForeignObjectShadowNode = ConcreteViewShadowNode<
    RNSVGForeignObjectComponentName,
    RNSVGForeignObjectProps>;


extern const char RNSVGImageComponentName[];

/*
 * `ShadowNode` for <RNSVGImage> component.
 */
using RNSVGImageShadowNode = ConcreteViewShadowNode<
    RNSVGImageComponentName,
    RNSVGImageProps>;


extern const char RNSVGMarkerComponentName[];

/*
 * `ShadowNode` for <RNSVGMarker> component.
 */
using RNSVGMarkerShadowNode = ConcreteViewShadowNode<
    RNSVGMarkerComponentName,
    RNSVGMarkerProps>;

extern const char RNSVGMaskComponentName[];

/*
 * `ShadowNode` for <RNSVGMask> component.
 */
using RNSVGMaskShadowNode = ConcreteViewShadowNode<
    RNSVGMaskComponentName,
    RNSVGMaskProps>;


extern const char RNSVGPatternComponentName[];

/*
 * `ShadowNode` for <RNSVGPattern> component.
 */
using RNSVGPatternShadowNode = ConcreteViewShadowNode<
    RNSVGPatternComponentName,
    RNSVGPatternProps>;

extern const char RNSVGRadialGradientComponentName[];

/*
 * `ShadowNode` for <RNSVGRadialGradient> component.
 */
using RNSVGRadialGradientShadowNode = ConcreteViewShadowNode<
    RNSVGRadialGradientComponentName,
    RNSVGRadialGradientProps>;



extern const char RNSVGSymbolComponentName[];

/*
 * `ShadowNode` for <RNSVGSymbol> component.
 */
using RNSVGSymbolShadowNode = ConcreteViewShadowNode<
    RNSVGSymbolComponentName,
    RNSVGSymbolProps>;

extern const char RNSVGTextComponentName[];

/*
 * `ShadowNode` for <RNSVGText> component.
 */
using RNSVGTextShadowNode = ConcreteViewShadowNode<
    RNSVGTextComponentName,
    RNSVGTextProps>;

extern const char RNSVGTextPathComponentName[];

/*
 * `ShadowNode` for <RNSVGTextPath> component.
 */
using RNSVGTextPathShadowNode = ConcreteViewShadowNode<
    RNSVGTextPathComponentName,
    RNSVGTextPathProps>;

extern const char RNSVGTSpanComponentName[];

/*
 * `ShadowNode` for <RNSVGTSpan> component.
 */
using RNSVGTSpanShadowNode = ConcreteViewShadowNode<
    RNSVGTSpanComponentName,
    RNSVGTSpanProps>;

} // namespace react
} // namespace facebook
