
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include <react/renderer/components/rnsvg/RNSVGShadowNodes.h>
#include <react/renderer/core/ConcreteComponentDescriptor.h>

namespace facebook {
namespace react {

using RNSVGSvgViewComponentDescriptor  = ConcreteComponentDescriptor<RNSVGSvgViewShadowNode>;
using RNSVGGroupComponentDescriptor = ConcreteComponentDescriptor<RNSVGGroupShadowNode>;
using RNSVGCircleComponentDescriptor = ConcreteComponentDescriptor<RNSVGCircleShadowNode>;
using RNSVGRectComponentDescriptor = ConcreteComponentDescriptor<RNSVGRectShadowNode>;
using RNSVGPathComponentDescriptor = ConcreteComponentDescriptor<RNSVGPathShadowNode>;
using RNSVGEllipseComponentDescriptor  = ConcreteComponentDescriptor<RNSVGEllipseShadowNode>;
using RNSVGLineComponentDescriptor  = ConcreteComponentDescriptor<RNSVGLineShadowNode>;
using RNSVGDefsComponentDescriptor  = ConcreteComponentDescriptor<RNSVGDefsShadowNode>;
using RNSVGUseComponentDescriptor  = ConcreteComponentDescriptor<RNSVGUseShadowNode>;
using RNSVGTextComponentDescriptor  = ConcreteComponentDescriptor<RNSVGTextShadowNode>;
using RNSVGTSpanComponentDescriptor  = ConcreteComponentDescriptor<RNSVGTSpanShadowNode>;
using RNSVGLinearGradientComponentDescriptor  = ConcreteComponentDescriptor<RNSVGLinearGradientShadowNode>;

} // namespace react
} // namespace facebook
