
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/rnsvg/RNSVGProps.h>
#include <react/renderer/components/image/conversions.h>
//#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

RNSVGCommonNodeProps::RNSVGCommonNodeProps(
    
    const RNSVGCommonNodeProps &sourceProps,
    const RawProps &rawProps): 

    name(convertRawProp( rawProps, "name", sourceProps.name, {})),
    matrix(convertRawProp( rawProps, "matrix", sourceProps.matrix, {})),
    mask(convertRawProp( rawProps, "mask", sourceProps.mask, {})),
    markerStart(convertRawProp( rawProps, "markerStart", sourceProps.markerStart, {})),
    markerMid(convertRawProp( rawProps, "markerMid", sourceProps.markerMid, {})),
    markerEnd(convertRawProp( rawProps, "markerEnd", sourceProps.markerEnd, {})),
    clipPath(convertRawProp( rawProps, "clipPath", sourceProps.clipPath, {})),
    clipRule(convertRawProp( rawProps, "clipRule", sourceProps.clipRule, {0})),
    responsible(convertRawProp( rawProps, "responsible", sourceProps.responsible, {false})),
    display(convertRawProp( rawProps, "display", sourceProps.display, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {}))
      {}

RNSVGCommonRenderableProps::RNSVGCommonRenderableProps(
    
    const RNSVGCommonRenderableProps &sourceProps,
    const RawProps &rawProps): 

    fill(convertRawProp( rawProps, "fill", sourceProps.fill, {})),
    fillOpacity(convertRawProp( rawProps, "fillOpacity", sourceProps.fillOpacity, {1.0})),
    fillRule(convertRawProp( rawProps, "fillRule", sourceProps.fillRule, {1})),
    stroke(convertRawProp( rawProps, "stroke", sourceProps.stroke, {})),
    strokeOpacity(convertRawProp( rawProps, "strokeOpacity", sourceProps.strokeOpacity, {1.0})),
    strokeWidth(convertRawProp( rawProps, "strokeWidth", sourceProps.strokeWidth, {"1"})),
    strokeLinecap(convertRawProp( rawProps, "strokeLinecap", sourceProps.strokeLinecap, {0})),
    strokeLinejoin(convertRawProp( rawProps, "strokeLinejoin", sourceProps.strokeLinejoin, {0})),
    strokeDasharray(convertRawProp( rawProps, "strokeDasharray", sourceProps.strokeDasharray, {})),
    strokeDashoffset(convertRawProp( rawProps, "strokeDashoffset", sourceProps.strokeDashoffset, {0.0})),
    strokeMiterlimit(convertRawProp( rawProps, "strokeMiterlimit", sourceProps.strokeMiterlimit, {0.0})),
    vectorEffect(convertRawProp( rawProps, "vectorEffect", sourceProps.vectorEffect, {0})),
    propList(convertRawProp( rawProps, "propList", sourceProps.propList, {}))
      {}

RNSVGGroupCommonrops::RNSVGGroupCommonrops(
    
    const RNSVGGroupCommonrops &sourceProps,
    const RawProps &rawProps):

    fontSize(convertRawProp( rawProps, "fontSize", sourceProps.fontSize, {})),
    fontWeight(convertRawProp( rawProps, "fontWeight", sourceProps.fontWeight, {})),
    font(convertRawProp( rawProps, "font", sourceProps.font, {}))
      {}

RNSVGCircleProps::RNSVGCircleProps(
    
    const RNSVGCircleProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    cx(convertRawProp( rawProps, "cx", sourceProps.cx, {})),
    cy(convertRawProp( rawProps, "cy", sourceProps.cy, {})),
    r(convertRawProp( rawProps, "r", sourceProps.r, {}))
      {}
RNSVGClipPathProps::RNSVGClipPathProps(
    
    const RNSVGClipPathProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0}))
      {}
RNSVGDefsProps::RNSVGDefsProps(
    
    const RNSVGDefsProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),RNSVGCommonNodeProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0}))
      {}
RNSVGEllipseProps::RNSVGEllipseProps(
    
    const RNSVGEllipseProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    cx(convertRawProp( rawProps, "cx", sourceProps.cx, {})),
    cy(convertRawProp( rawProps, "cy", sourceProps.cy, {})),
    rx(convertRawProp( rawProps, "rx", sourceProps.rx, {})),
    ry(convertRawProp( rawProps, "ry", sourceProps.ry, {}))
      {}
RNSVGForeignObjectProps::RNSVGForeignObjectProps(
    
    const RNSVGForeignObjectProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    height(convertRawProp( rawProps, "height", sourceProps.height, {})),
    width(convertRawProp( rawProps, "width", sourceProps.width, {}))
      {}
RNSVGGroupProps::RNSVGGroupProps(
    
    const RNSVGGroupProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0}))
      {}
RNSVGImageProps::RNSVGImageProps(
    
    const RNSVGImageProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    width(convertRawProp( rawProps, "width", sourceProps.width, {})),
    height(convertRawProp( rawProps, "height", sourceProps.height, {})),
    src(convertRawProp( rawProps, "src", sourceProps.src, {})),
    align(convertRawProp( rawProps, "align", sourceProps.align, {})),
    meetOrSlice(convertRawProp( rawProps, "meetOrSlice", sourceProps.meetOrSlice, {0}))
      {}
RNSVGLinearGradientProps::RNSVGLinearGradientProps(
    
    const RNSVGLinearGradientProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),RNSVGCommonNodeProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    x1(convertRawProp( rawProps, "x1", sourceProps.x1, {})),
    y1(convertRawProp( rawProps, "y1", sourceProps.y1, {})),
    x2(convertRawProp( rawProps, "x2", sourceProps.x2, {})),
    y2(convertRawProp( rawProps, "y2", sourceProps.y2, {})),
    gradient(convertRawProp( rawProps, "gradient", sourceProps.gradient, {})),
    gradientUnits(convertRawProp( rawProps, "gradientUnits", sourceProps.gradientUnits, {0})),
    gradientTransform(convertRawProp( rawProps, "gradientTransform", sourceProps.gradientTransform, {}))
      {}
RNSVGLineProps::RNSVGLineProps(
    
    const RNSVGLineProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    x1(convertRawProp( rawProps, "x1", sourceProps.x1, {})),
    y1(convertRawProp( rawProps, "y1", sourceProps.y1, {})),
    x2(convertRawProp( rawProps, "x2", sourceProps.x2, {})),
    y2(convertRawProp( rawProps, "y2", sourceProps.y2, {}))
      {}
RNSVGMarkerProps::RNSVGMarkerProps(
    
    const RNSVGMarkerProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    refX(convertRawProp( rawProps, "refX", sourceProps.refX, {})),
    refY(convertRawProp( rawProps, "refY", sourceProps.refY, {})),
    markerHeight(convertRawProp( rawProps, "markerHeight", sourceProps.markerHeight, {})),
    markerWidth(convertRawProp( rawProps, "markerWidth", sourceProps.markerWidth, {})),
    markerUnits(convertRawProp( rawProps, "markerUnits", sourceProps.markerUnits, {})),
    orient(convertRawProp( rawProps, "orient", sourceProps.orient, {})),
    minX(convertRawProp( rawProps, "minX", sourceProps.minX, {0.0})),
    minY(convertRawProp( rawProps, "minY", sourceProps.minY, {0.0})),
    vbWidth(convertRawProp( rawProps, "vbWidth", sourceProps.vbWidth, {0.0})),
    vbHeight(convertRawProp( rawProps, "vbHeight", sourceProps.vbHeight, {0.0})),
    align(convertRawProp( rawProps, "align", sourceProps.align, {})),
    meetOrSlice(convertRawProp( rawProps, "meetOrSlice", sourceProps.meetOrSlice, {0}))
      {}
RNSVGMaskProps::RNSVGMaskProps(
    
    const RNSVGMaskProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    height(convertRawProp( rawProps, "height", sourceProps.height, {})),
    width(convertRawProp( rawProps, "width", sourceProps.width, {})),
    maskUnits(convertRawProp( rawProps, "maskUnits", sourceProps.maskUnits, {0})),
    maskContentUnits(convertRawProp( rawProps, "maskContentUnits", sourceProps.maskContentUnits, {0})),
    maskTransform(convertRawProp( rawProps, "maskTransform", sourceProps.maskTransform, {}))
      {}
RNSVGPathProps::RNSVGPathProps(
    
    const RNSVGPathProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    d(convertRawProp( rawProps, "d", sourceProps.d, {}))
      {}
RNSVGPatternProps::RNSVGPatternProps(
    
    const RNSVGPatternProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    height(convertRawProp( rawProps, "height", sourceProps.height, {})),
    width(convertRawProp( rawProps, "width", sourceProps.width, {})),
    patternUnits(convertRawProp( rawProps, "patternUnits", sourceProps.patternUnits, {0})),
    patternContentUnits(convertRawProp( rawProps, "patternContentUnits", sourceProps.patternContentUnits, {0})),
    patternTransform(convertRawProp( rawProps, "patternTransform", sourceProps.patternTransform, {})),
    minX(convertRawProp( rawProps, "minX", sourceProps.minX, {0.0})),
    minY(convertRawProp( rawProps, "minY", sourceProps.minY, {0.0})),
    vbWidth(convertRawProp( rawProps, "vbWidth", sourceProps.vbWidth, {0.0})),
    vbHeight(convertRawProp( rawProps, "vbHeight", sourceProps.vbHeight, {0.0})),
    align(convertRawProp( rawProps, "align", sourceProps.align, {})),
    meetOrSlice(convertRawProp( rawProps, "meetOrSlice", sourceProps.meetOrSlice, {0}))
      {}
RNSVGRadialGradientProps::RNSVGRadialGradientProps(
    
    const RNSVGRadialGradientProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),RNSVGCommonNodeProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    fx(convertRawProp( rawProps, "fx", sourceProps.fx, {})),
    fy(convertRawProp( rawProps, "fy", sourceProps.fy, {})),
    cx(convertRawProp( rawProps, "cx", sourceProps.cx, {})),
    cy(convertRawProp( rawProps, "cy", sourceProps.cy, {})),
    rx(convertRawProp( rawProps, "rx", sourceProps.rx, {})),
    ry(convertRawProp( rawProps, "ry", sourceProps.ry, {})),
    gradient(convertRawProp( rawProps, "gradient", sourceProps.gradient, {})),
    gradientUnits(convertRawProp( rawProps, "gradientUnits", sourceProps.gradientUnits, {0})),
    gradientTransform(convertRawProp( rawProps, "gradientTransform", sourceProps.gradientTransform, {}))
      {}
RNSVGRectProps::RNSVGRectProps(
    
    const RNSVGRectProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    height(convertRawProp( rawProps, "height", sourceProps.height, {})),
    width(convertRawProp( rawProps, "width", sourceProps.width, {})),
    rx(convertRawProp( rawProps, "rx", sourceProps.rx, {})),
    ry(convertRawProp( rawProps, "ry", sourceProps.ry, {}))
      {}
RNSVGSvgViewProps::RNSVGSvgViewProps(
    
    const RNSVGSvgViewProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),

    bbWidth(convertRawProp( rawProps, "bbWidth", sourceProps.bbWidth, {})),
    bbHeight(convertRawProp( rawProps, "bbHeight", sourceProps.bbHeight, {})),
    minX(convertRawProp( rawProps, "minX", sourceProps.minX, {0.0})),
    minY(convertRawProp( rawProps, "minY", sourceProps.minY, {0.0})),
    vbWidth(convertRawProp( rawProps, "vbWidth", sourceProps.vbWidth, {0.0})),
    vbHeight(convertRawProp( rawProps, "vbHeight", sourceProps.vbHeight, {0.0})),
    align(convertRawProp( rawProps, "align", sourceProps.align, {})),
    meetOrSlice(convertRawProp( rawProps, "meetOrSlice", sourceProps.meetOrSlice, {0})),
   // tintColor(convertRawProp( rawProps, "tintColor", sourceProps.tintColor, {})),
    color(convertRawProp( rawProps, "color", sourceProps.color, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {}))
      {}
RNSVGSymbolProps::RNSVGSymbolProps(
    
    const RNSVGSymbolProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    minX(convertRawProp( rawProps, "minX", sourceProps.minX, {0.0})),
    minY(convertRawProp( rawProps, "minY", sourceProps.minY, {0.0})),
    vbWidth(convertRawProp( rawProps, "vbWidth", sourceProps.vbWidth, {0.0})),
    vbHeight(convertRawProp( rawProps, "vbHeight", sourceProps.vbHeight, {0.0})),
    align(convertRawProp( rawProps, "align", sourceProps.align, {})),
    meetOrSlice(convertRawProp( rawProps, "meetOrSlice", sourceProps.meetOrSlice, {0}))
      {}
RNSVGTextProps::RNSVGTextProps(
    
    const RNSVGTextProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    dx(convertRawProp( rawProps, "dx", sourceProps.dx, {})),
    dy(convertRawProp( rawProps, "dy", sourceProps.dy, {})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    rotate(convertRawProp( rawProps, "rotate", sourceProps.rotate, {})),
    inlineSize(convertRawProp( rawProps, "inlineSize", sourceProps.inlineSize, {})),
    textLength(convertRawProp( rawProps, "textLength", sourceProps.textLength, {})),
    baselineShift(convertRawProp( rawProps, "baselineShift", sourceProps.baselineShift, {})),
    lengthAdjust(convertRawProp( rawProps, "lengthAdjust", sourceProps.lengthAdjust, {})),
    alignmentBaseline(convertRawProp( rawProps, "alignmentBaseline", sourceProps.alignmentBaseline, {})),
    verticalAlign(convertRawProp( rawProps, "verticalAlign", sourceProps.verticalAlign, {}))
      {}
RNSVGTextPathProps::RNSVGTextPathProps(
    
    const RNSVGTextPathProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    dx(convertRawProp( rawProps, "dx", sourceProps.dx, {})),
    dy(convertRawProp( rawProps, "dy", sourceProps.dy, {})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    rotate(convertRawProp( rawProps, "rotate", sourceProps.rotate, {})),
    inlineSize(convertRawProp( rawProps, "inlineSize", sourceProps.inlineSize, {})),
    textLength(convertRawProp( rawProps, "textLength", sourceProps.textLength, {})),
    baselineShift(convertRawProp( rawProps, "baselineShift", sourceProps.baselineShift, {})),
    lengthAdjust(convertRawProp( rawProps, "lengthAdjust", sourceProps.lengthAdjust, {})),
    alignmentBaseline(convertRawProp( rawProps, "alignmentBaseline", sourceProps.alignmentBaseline, {})),
    verticalAlign(convertRawProp( rawProps, "verticalAlign", sourceProps.verticalAlign, {})),
    href(convertRawProp( rawProps, "href", sourceProps.href, {})),
    side(convertRawProp( rawProps, "side", sourceProps.side, {})),
    method(convertRawProp( rawProps, "method", sourceProps.method, {})),
    midLine(convertRawProp( rawProps, "midLine", sourceProps.midLine, {})),
    spacing(convertRawProp( rawProps, "spacing", sourceProps.spacing, {})),
    startOffset(convertRawProp( rawProps, "startOffset", sourceProps.startOffset, {}))
      {}
RNSVGTSpanProps::RNSVGTSpanProps(
    
    const RNSVGTSpanProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),
                               RNSVGGroupCommonrops(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    dx(convertRawProp( rawProps, "dx", sourceProps.dx, {})),
    dy(convertRawProp( rawProps, "dy", sourceProps.dy, {})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    rotate(convertRawProp( rawProps, "rotate", sourceProps.rotate, {})),
    inlineSize(convertRawProp( rawProps, "inlineSize", sourceProps.inlineSize, {})),
    textLength(convertRawProp( rawProps, "textLength", sourceProps.textLength, {})),
    baselineShift(convertRawProp( rawProps, "baselineShift", sourceProps.baselineShift, {})),
    lengthAdjust(convertRawProp( rawProps, "lengthAdjust", sourceProps.lengthAdjust, {})),
    alignmentBaseline(convertRawProp( rawProps, "alignmentBaseline", sourceProps.alignmentBaseline, {})),
    verticalAlign(convertRawProp( rawProps, "verticalAlign", sourceProps.verticalAlign, {})),
    content(convertRawProp( rawProps, "content", sourceProps.content, {}))
      {}
RNSVGUseProps::RNSVGUseProps(
    
    const RNSVGUseProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps), 
                               RNSVGCommonNodeProps(sourceProps, rawProps),
                               RNSVGCommonRenderableProps(sourceProps, rawProps),

    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    href(convertRawProp( rawProps, "href", sourceProps.href, {})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    height(convertRawProp( rawProps, "height", sourceProps.height, {})),
    width(convertRawProp( rawProps, "width", sourceProps.width, {}))
      {}

} // namespace react
} // namespace facebook
