
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/rnsvg/RNSVGProps.h>
#include <react/renderer/components/image/conversions.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

RNSVGCircleProps::RNSVGCircleProps(
    const RNSVGCircleProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),

    name(convertRawProp( rawProps, "name", sourceProps.name, {})),
    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    matrix(convertRawProp( rawProps, "matrix", sourceProps.matrix, {})),
    mask(convertRawProp( rawProps, "mask", sourceProps.mask, {})),
    markerStart(convertRawProp( rawProps, "markerStart", sourceProps.markerStart, {})),
    markerMid(convertRawProp( rawProps, "markerMid", sourceProps.markerMid, {})),
    markerEnd(convertRawProp( rawProps, "markerEnd", sourceProps.markerEnd, {})),
    clipPath(convertRawProp( rawProps, "clipPath", sourceProps.clipPath, {})),
    clipRule(convertRawProp( rawProps, "clipRule", sourceProps.clipRule, {0})),
    responsible(convertRawProp( rawProps, "responsible", sourceProps.responsible, {false})),
    display(convertRawProp( rawProps, "display", sourceProps.display, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {})),
    fill(convertRawProp( rawProps, "fill", sourceProps.fill, {})),
    fillOpacity(convertRawProp( rawProps, "fillOpacity", sourceProps.fillOpacity, {1.0})),
    fillRule(convertRawProp( rawProps, "fillRule", sourceProps.fillRule, {1})),
    stroke(convertRawProp( rawProps, "stroke", sourceProps.stroke, {})),
    strokeOpacity(convertRawProp( rawProps, "strokeOpacity", sourceProps.strokeOpacity, {1.0})),
    strokeWidth(convertRawProp( rawProps, "strokeWidth", sourceProps.strokeWidth, {"1"})),
    strokeLinecap(convertRawProp( rawProps, "strokeLinecap", sourceProps.strokeLinecap, {0})),
    strokeLinejoin(convertRawProp( rawProps, "strokeLinejoin", sourceProps.strokeLinejoin, {0})),
    strokeDasharray(convertRawProp( rawProps, "strokeDasharray", sourceProps.strokeDasharray, {})),
    strokeDashoffset(convertRawProp( rawProps, "strokeDashoffset", sourceProps.strokeDashoffset, {0.0})),
    strokeMiterlimit(convertRawProp( rawProps, "strokeMiterlimit", sourceProps.strokeMiterlimit, {0.0})),
    vectorEffect(convertRawProp( rawProps, "vectorEffect", sourceProps.vectorEffect, {0})),
    propList(convertRawProp( rawProps, "propList", sourceProps.propList, {})),
    cx(convertRawProp( rawProps, "cx", sourceProps.cx, {})),
    cy(convertRawProp( rawProps, "cy", sourceProps.cy, {})),
    r(convertRawProp( rawProps, "r", sourceProps.r, {}))
      {}

RNSVGGroupProps::RNSVGGroupProps(
    const RNSVGGroupProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),

    name(convertRawProp( rawProps, "name", sourceProps.name, {})),
    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    matrix(convertRawProp( rawProps, "matrix", sourceProps.matrix, {})),
    mask(convertRawProp( rawProps, "mask", sourceProps.mask, {})),
    markerStart(convertRawProp( rawProps, "markerStart", sourceProps.markerStart, {})),
    markerMid(convertRawProp( rawProps, "markerMid", sourceProps.markerMid, {})),
    markerEnd(convertRawProp( rawProps, "markerEnd", sourceProps.markerEnd, {})),
    clipPath(convertRawProp( rawProps, "clipPath", sourceProps.clipPath, {})),
    clipRule(convertRawProp( rawProps, "clipRule", sourceProps.clipRule, {0})),
    responsible(convertRawProp( rawProps, "responsible", sourceProps.responsible, {false})),
    display(convertRawProp( rawProps, "display", sourceProps.display, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {})),
    fill(convertRawProp( rawProps, "fill", sourceProps.fill, {})),
    fillOpacity(convertRawProp( rawProps, "fillOpacity", sourceProps.fillOpacity, {1.0})),
    fillRule(convertRawProp( rawProps, "fillRule", sourceProps.fillRule, {1})),
    stroke(convertRawProp( rawProps, "stroke", sourceProps.stroke, {})),
    strokeOpacity(convertRawProp( rawProps, "strokeOpacity", sourceProps.strokeOpacity, {1.0})),
    strokeWidth(convertRawProp( rawProps, "strokeWidth", sourceProps.strokeWidth, {"1"})),
    strokeLinecap(convertRawProp( rawProps, "strokeLinecap", sourceProps.strokeLinecap, {0})),
    strokeLinejoin(convertRawProp( rawProps, "strokeLinejoin", sourceProps.strokeLinejoin, {0})),
    strokeDasharray(convertRawProp( rawProps, "strokeDasharray", sourceProps.strokeDasharray, {})),
    strokeDashoffset(convertRawProp( rawProps, "strokeDashoffset", sourceProps.strokeDashoffset, {0.0})),
    strokeMiterlimit(convertRawProp( rawProps, "strokeMiterlimit", sourceProps.strokeMiterlimit, {0.0})),
    vectorEffect(convertRawProp( rawProps, "vectorEffect", sourceProps.vectorEffect, {0})),
    propList(convertRawProp( rawProps, "propList", sourceProps.propList, {})),
    fontSize(convertRawProp( rawProps, "fontSize", sourceProps.fontSize, {})),
    fontWeight(convertRawProp( rawProps, "fontWeight", sourceProps.fontWeight, {})),
    font(convertRawProp( rawProps, "font", sourceProps.font, {}))
      {}


RNSVGPathProps::RNSVGPathProps(
    const RNSVGPathProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),

    name(convertRawProp( rawProps, "name", sourceProps.name, {})),
    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    matrix(convertRawProp( rawProps, "matrix", sourceProps.matrix, {})),
    mask(convertRawProp( rawProps, "mask", sourceProps.mask, {})),
    markerStart(convertRawProp( rawProps, "markerStart", sourceProps.markerStart, {})),
    markerMid(convertRawProp( rawProps, "markerMid", sourceProps.markerMid, {})),
    markerEnd(convertRawProp( rawProps, "markerEnd", sourceProps.markerEnd, {})),
    clipPath(convertRawProp( rawProps, "clipPath", sourceProps.clipPath, {})),
    clipRule(convertRawProp( rawProps, "clipRule", sourceProps.clipRule, {0})),
    responsible(convertRawProp( rawProps, "responsible", sourceProps.responsible, {false})),
    display(convertRawProp( rawProps, "display", sourceProps.display, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {})),
    fill(convertRawProp( rawProps, "fill", sourceProps.fill, {})),
    fillOpacity(convertRawProp( rawProps, "fillOpacity", sourceProps.fillOpacity, {1.0})),
    fillRule(convertRawProp( rawProps, "fillRule", sourceProps.fillRule, {1})),
    stroke(convertRawProp( rawProps, "stroke", sourceProps.stroke, {})),
    strokeOpacity(convertRawProp( rawProps, "strokeOpacity", sourceProps.strokeOpacity, {1.0})),
    strokeWidth(convertRawProp( rawProps, "strokeWidth", sourceProps.strokeWidth, {"1"})),
    strokeLinecap(convertRawProp( rawProps, "strokeLinecap", sourceProps.strokeLinecap, {0})),
    strokeLinejoin(convertRawProp( rawProps, "strokeLinejoin", sourceProps.strokeLinejoin, {0})),
    strokeDasharray(convertRawProp( rawProps, "strokeDasharray", sourceProps.strokeDasharray, {})),
    strokeDashoffset(convertRawProp( rawProps, "strokeDashoffset", sourceProps.strokeDashoffset, {0.0})),
    strokeMiterlimit(convertRawProp( rawProps, "strokeMiterlimit", sourceProps.strokeMiterlimit, {0.0})),
    vectorEffect(convertRawProp( rawProps, "vectorEffect", sourceProps.vectorEffect, {0})),
    propList(convertRawProp( rawProps, "propList", sourceProps.propList, {})),
    d(convertRawProp( rawProps, "d", sourceProps.d, {}))
      {}

RNSVGRectProps::RNSVGRectProps(
    const RNSVGRectProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),

    name(convertRawProp( rawProps, "name", sourceProps.name, {})),
    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    matrix(convertRawProp( rawProps, "matrix", sourceProps.matrix, {})),
    mask(convertRawProp( rawProps, "mask", sourceProps.mask, {})),
    markerStart(convertRawProp( rawProps, "markerStart", sourceProps.markerStart, {})),
    markerMid(convertRawProp( rawProps, "markerMid", sourceProps.markerMid, {})),
    markerEnd(convertRawProp( rawProps, "markerEnd", sourceProps.markerEnd, {})),
    clipPath(convertRawProp( rawProps, "clipPath", sourceProps.clipPath, {})),
    clipRule(convertRawProp( rawProps, "clipRule", sourceProps.clipRule, {0})),
    responsible(convertRawProp( rawProps, "responsible", sourceProps.responsible, {false})),
    display(convertRawProp( rawProps, "display", sourceProps.display, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {})),
    fill(convertRawProp( rawProps, "fill", sourceProps.fill, {})),
    fillOpacity(convertRawProp( rawProps, "fillOpacity", sourceProps.fillOpacity, {1.0})),
    fillRule(convertRawProp( rawProps, "fillRule", sourceProps.fillRule, {1})),
    stroke(convertRawProp( rawProps, "stroke", sourceProps.stroke, {})),
    strokeOpacity(convertRawProp( rawProps, "strokeOpacity", sourceProps.strokeOpacity, {1.0})),
    strokeWidth(convertRawProp( rawProps, "strokeWidth", sourceProps.strokeWidth, {"1"})),
    strokeLinecap(convertRawProp( rawProps, "strokeLinecap", sourceProps.strokeLinecap, {0})),
    strokeLinejoin(convertRawProp( rawProps, "strokeLinejoin", sourceProps.strokeLinejoin, {0})),
    strokeDasharray(convertRawProp( rawProps, "strokeDasharray", sourceProps.strokeDasharray, {})),
    strokeDashoffset(convertRawProp( rawProps, "strokeDashoffset", sourceProps.strokeDashoffset, {0.0})),
    strokeMiterlimit(convertRawProp( rawProps, "strokeMiterlimit", sourceProps.strokeMiterlimit, {0.0})),
    vectorEffect(convertRawProp( rawProps, "vectorEffect", sourceProps.vectorEffect, {0})),
    propList(convertRawProp( rawProps, "propList", sourceProps.propList, {})),
    x(convertRawProp( rawProps, "x", sourceProps.x, {})),
    y(convertRawProp( rawProps, "y", sourceProps.y, {})),
    height(convertRawProp( rawProps, "height", sourceProps.height, {})),
    width(convertRawProp( rawProps, "width", sourceProps.width, {})),
    rx(convertRawProp( rawProps, "rx", sourceProps.rx, {})),
    ry(convertRawProp( rawProps, "ry", sourceProps.ry, {}))
      {}
RNSVGLinearGradientProps::RNSVGLinearGradientProps(
    const RNSVGLinearGradientProps &sourceProps,
    const RawProps &rawProps): ViewProps( sourceProps, rawProps),

    name(convertRawProp( rawProps, "name", sourceProps.name, {})),
    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    matrix(convertRawProp( rawProps, "matrix", sourceProps.matrix, {})),
    mask(convertRawProp( rawProps, "mask", sourceProps.mask, {})),
    markerStart(convertRawProp( rawProps, "markerStart", sourceProps.markerStart, {})),
    markerMid(convertRawProp( rawProps, "markerMid", sourceProps.markerMid, {})),
    markerEnd(convertRawProp( rawProps, "markerEnd", sourceProps.markerEnd, {})),
    clipPath(convertRawProp( rawProps, "clipPath", sourceProps.clipPath, {})),
    clipRule(convertRawProp( rawProps, "clipRule", sourceProps.clipRule, {0})),
    responsible(convertRawProp( rawProps, "responsible", sourceProps.responsible, {false})),
    display(convertRawProp( rawProps, "display", sourceProps.display, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {})),
    x1(convertRawProp( rawProps, "x1", sourceProps.x1, {})),
    y1(convertRawProp( rawProps, "y1", sourceProps.y1, {})),
    x2(convertRawProp( rawProps, "x2", sourceProps.x2, {})),
    y2(convertRawProp( rawProps, "y2", sourceProps.y2, {})),
    gradient(convertRawProp( rawProps, "gradient", sourceProps.gradient, {})),
    gradientUnits(convertRawProp( rawProps, "gradientUnits", sourceProps.gradientUnits, {0})),
    gradientTransform(convertRawProp( rawProps, "gradientTransform", sourceProps.gradientTransform, {}))
      {}

RNSVGEllipseProps::RNSVGEllipseProps(
    const RNSVGEllipseProps &sourceProps,
    const RawProps &rawProps): ViewProps(sourceProps, rawProps),

    name(convertRawProp( rawProps, "name", sourceProps.name, {})),
    opacity(convertRawProp( rawProps, "opacity", sourceProps.opacity, {1.0})),
    matrix(convertRawProp( rawProps, "matrix", sourceProps.matrix, {})),
    mask(convertRawProp( rawProps, "mask", sourceProps.mask, {})),
    markerStart(convertRawProp( rawProps, "markerStart", sourceProps.markerStart, {})),
    markerMid(convertRawProp( rawProps, "markerMid", sourceProps.markerMid, {})),
    markerEnd(convertRawProp( rawProps, "markerEnd", sourceProps.markerEnd, {})),
    clipPath(convertRawProp( rawProps, "clipPath", sourceProps.clipPath, {})),
    clipRule(convertRawProp( rawProps, "clipRule", sourceProps.clipRule, {0})),
    responsible(convertRawProp( rawProps, "responsible", sourceProps.responsible, {false})),
    display(convertRawProp( rawProps, "display", sourceProps.display, {})),
    pointerEvents(convertRawProp( rawProps, "pointerEvents", sourceProps.pointerEvents, {})),
    fill(convertRawProp( rawProps, "fill", sourceProps.fill, {})),
    fillOpacity(convertRawProp( rawProps, "fillOpacity", sourceProps.fillOpacity, {1.0})),
    fillRule(convertRawProp( rawProps, "fillRule", sourceProps.fillRule, {1})),
    stroke(convertRawProp( rawProps, "stroke", sourceProps.stroke, {})),
    strokeOpacity(convertRawProp( rawProps, "strokeOpacity", sourceProps.strokeOpacity, {1.0})),
    strokeWidth(convertRawProp( rawProps, "strokeWidth", sourceProps.strokeWidth, {"1"})),
    strokeLinecap(convertRawProp( rawProps, "strokeLinecap", sourceProps.strokeLinecap, {0})),
    strokeLinejoin(convertRawProp( rawProps, "strokeLinejoin", sourceProps.strokeLinejoin, {0})),
    strokeDasharray(convertRawProp( rawProps, "strokeDasharray", sourceProps.strokeDasharray, {})),
    strokeDashoffset(convertRawProp( rawProps, "strokeDashoffset", sourceProps.strokeDashoffset, {0.0})),
    strokeMiterlimit(convertRawProp( rawProps, "strokeMiterlimit", sourceProps.strokeMiterlimit, {0.0})),
    vectorEffect(convertRawProp( rawProps, "vectorEffect", sourceProps.vectorEffect, {0})),
    propList(convertRawProp(rawProps, "propList", sourceProps.propList, {})),
    cx(convertRawProp(rawProps, "cx", sourceProps.cx, {})),
    cy(convertRawProp(rawProps, "cy", sourceProps.cy, {})),
    rx(convertRawProp(rawProps, "rx", sourceProps.rx, {})),
    ry(convertRawProp(rawProps, "ry", sourceProps.ry, {}))
      {}

} // namespace react
} // namespace facebook
